chore: let's test only github app

diff --git a/.github/workflows/test-action.yml b/.github/workflows/test-action.yml
--- a/.github/workflows/test-action.yml
+++ b/.github/workflows/test-action.yml
@@ -1,4 +1,4 @@
-name: "Test Action"
+name: 'Test Action'
 
 on:
   workflow_dispatch:
@@ -36,106 +36,106 @@ jobs:
     needs:
       - unit-test-action
     steps:
-      - name: "[1] (token) Run Simple Trigger And Wait"
-        id: run-simple-trigger-and-wait
-        uses: dragoscops/workflow-trigger-wait@github_app_token
-        with:
-          credentials: '{ "token": "${{ secrets.GH_TOKEN }}" }'
-          repo: ${{ github.repository }}
-          workflow_id: "test-workflow.yml"
-          ref: "main"
-          inputs: '{"Timeout": "5"}'
-          wait_interval: "10000"
-          timeout: "60000"
-          action: "trigger-and-wait"
-          debug: "yes"
+      # - name: "[1] (token) Run Simple Trigger And Wait"
+      #   id: run-simple-trigger-and-wait
+      #   uses: dragoscops/workflow-trigger-wait@github_app_token
+      #   with:
+      #     credentials: '{ "token": "${{ secrets.GH_TOKEN }}" }'
+      #     repo: ${{ github.repository }}
+      #     workflow_id: "test-workflow.yml"
+      #     ref: "main"
+      #     inputs: '{"Timeout": "5"}'
+      #     wait_interval: "10000"
+      #     timeout: "60000"
+      #     action: "trigger-and-wait"
+      #     debug: "yes"
 
-      - name: "[1] (token) Verify Outputs"
-        run: |
-          echo "Run Conclusion: ${{ steps.run-simple-trigger-and-wait.outputs.run_conclusion }}"
-          if [[ "${{ steps.run-simple-trigger-and-wait.outputs.run_conclusion }}" != "success" ]]; then exit 1; fi
+      # - name: "[1] (token) Verify Outputs"
+      #   run: |
+      #     echo "Run Conclusion: ${{ steps.run-simple-trigger-and-wait.outputs.run_conclusion }}"
+      #     if [[ "${{ steps.run-simple-trigger-and-wait.outputs.run_conclusion }}" != "success" ]]; then exit 1; fi
 
-      - name: "[2] (token) Run Trigger Only"
-        id: run-trigger-only
-        uses: dragoscops/workflow-trigger-wait@github_app_token
-        with:
-          credentials: '{ "token": "${{ secrets.GH_TOKEN }}" }'
-          repo: ${{ github.repository }}
-          workflow_id: "test-workflow.yml"
-          ref: "main"
-          inputs: '{"Timeout": "5"}'
-          wait_interval: "10000"
-          timeout: "60000"
-          action: "trigger-only"
-          debug: "yes"
+      # - name: "[2] (token) Run Trigger Only"
+      #   id: run-trigger-only
+      #   uses: dragoscops/workflow-trigger-wait@github_app_token
+      #   with:
+      #     credentials: '{ "token": "${{ secrets.GH_TOKEN }}" }'
+      #     repo: ${{ github.repository }}
+      #     workflow_id: "test-workflow.yml"
+      #     ref: "main"
+      #     inputs: '{"Timeout": "5"}'
+      #     wait_interval: "10000"
+      #     timeout: "60000"
+      #     action: "trigger-only"
+      #     debug: "yes"
 
-      - name: "[2] (token) Verify Outputs"
-        run: |
-          echo "Run Id: ${{ steps.run-trigger-only.outputs.run_id }}"
-          echo "Run Conclusion: ${{ steps.run-trigger-only.outputs.run_conclusion }}"
-          if [[ "${{ steps.run-trigger-only.outputs.run_conclusion }}" != "success" ]]; then exit 1; fi
+      # - name: "[2] (token) Verify Outputs"
+      #   run: |
+      #     echo "Run Id: ${{ steps.run-trigger-only.outputs.run_id }}"
+      #     echo "Run Conclusion: ${{ steps.run-trigger-only.outputs.run_conclusion }}"
+      #     if [[ "${{ steps.run-trigger-only.outputs.run_conclusion }}" != "success" ]]; then exit 1; fi
 
-      - name: "[3] (token) Run Wait Only"
-        id: run-wait-only
-        uses: dragoscops/workflow-trigger-wait@github_app_token
-        with:
-          credentials: '{ "token": "${{ secrets.GH_TOKEN }}" }'
-          repo: ${{ github.repository }}
-          workflow_id: "test-workflow.yml"
-          ref: "main"
-          inputs: '{"Timeout": "5"}'
-          wait_interval: "10000"
-          timeout: "60000"
-          action: "wait-only"
-          debug: "yes"
-          run_id: "${{ steps.run-trigger-only.outputs.run_id }}"
+      # - name: "[3] (token) Run Wait Only"
+      #   id: run-wait-only
+      #   uses: dragoscops/workflow-trigger-wait@github_app_token
+      #   with:
+      #     credentials: '{ "token": "${{ secrets.GH_TOKEN }}" }'
+      #     repo: ${{ github.repository }}
+      #     workflow_id: "test-workflow.yml"
+      #     ref: "main"
+      #     inputs: '{"Timeout": "5"}'
+      #     wait_interval: "10000"
+      #     timeout: "60000"
+      #     action: "wait-only"
+      #     debug: "yes"
+      #     run_id: "${{ steps.run-trigger-only.outputs.run_id }}"
 
-      - name: "[3] (token) Verify Outputs"
-        run: |
-          echo "Run Conclusion: ${{ steps.run-wait-only.outputs.run_conclusion }}"
-          if [[ "${{ steps.run-wait-only.outputs.run_conclusion }}" != "success" ]]; then exit 1; fi
+      # - name: "[3] (token) Verify Outputs"
+      #   run: |
+      #     echo "Run Conclusion: ${{ steps.run-wait-only.outputs.run_conclusion }}"
+      #     if [[ "${{ steps.run-wait-only.outputs.run_conclusion }}" != "success" ]]; then exit 1; fi
 
-      - name: "[4] (token) Run Timeout Trigger And Wait"
-        id: run-throw-trigger-and-wait
-        uses: dragoscops/workflow-trigger-wait@github_app_token
-        with:
-          credentials: '{ "token": "${{ secrets.GH_TOKEN }}" }'
-          repo: ${{ github.repository }}
-          workflow_id: "test-workflow.yml"
-          ref: "main"
-          inputs: '{"Timeout": "5", "Throw": "yes"}'
-          wait_interval: "10000"
-          timeout: "60000"
-          action: "trigger-and-wait"
-          debug: "yes"
-          no_throw: "yes"
+      # - name: "[4] (token) Run Timeout Trigger And Wait"
+      #   id: run-throw-trigger-and-wait
+      #   uses: dragoscops/workflow-trigger-wait@github_app_token
+      #   with:
+      #     credentials: '{ "token": "${{ secrets.GH_TOKEN }}" }'
+      #     repo: ${{ github.repository }}
+      #     workflow_id: "test-workflow.yml"
+      #     ref: "main"
+      #     inputs: '{"Timeout": "5", "Throw": "yes"}'
+      #     wait_interval: "10000"
+      #     timeout: "60000"
+      #     action: "trigger-and-wait"
+      #     debug: "yes"
+      #     no_throw: "yes"
 
-      - name: "[4] (token) Verify Outputs"
-        run: |
-          echo "Run Conclusion: ${{ steps.run-throw-trigger-and-wait.outputs.run_conclusion }}"
-          if [[ "${{ steps.run-throw-trigger-and-wait.outputs.run_conclusion }}" != "failure" ]]; then exit 1; fi
+      # - name: "[4] (token) Verify Outputs"
+      #   run: |
+      #     echo "Run Conclusion: ${{ steps.run-throw-trigger-and-wait.outputs.run_conclusion }}"
+      #     if [[ "${{ steps.run-throw-trigger-and-wait.outputs.run_conclusion }}" != "failure" ]]; then exit 1; fi
 
-      - name: "[5] (token) Run Timeout Trigger And Wait"
-        id: run-timeout-trigger-and-wait
-        uses: dragoscops/workflow-trigger-wait@github_app_token
-        with:
-          credentials: '{ "token": "${{ secrets.GH_TOKEN }}" }'
-          repo: ${{ github.repository }}
-          workflow_id: "test-workflow.yml"
-          ref: "main"
-          inputs: '{"Timeout": "5"}'
-          wait_interval: "1000"
-          timeout: "3000"
-          action: "trigger-and-wait"
-          debug: "yes"
-          no_throw: "yes"
+      # - name: "[5] (token) Run Timeout Trigger And Wait"
+      #   id: run-timeout-trigger-and-wait
+      #   uses: dragoscops/workflow-trigger-wait@github_app_token
+      #   with:
+      #     credentials: '{ "token": "${{ secrets.GH_TOKEN }}" }'
+      #     repo: ${{ github.repository }}
+      #     workflow_id: "test-workflow.yml"
+      #     ref: "main"
+      #     inputs: '{"Timeout": "5"}'
+      #     wait_interval: "1000"
+      #     timeout: "3000"
+      #     action: "trigger-and-wait"
+      #     debug: "yes"
+      #     no_throw: "yes"
 
-      - name: "[5] (token) Verify Outputs"
-        run: |
-          echo "Run Conclusion: ${{ steps.run-timeout-trigger-and-wait.outputs.run_conclusion }}"
-          if [[ "${{ steps.run-timeout-trigger-and-wait.outputs.run_conclusion }}" != "timeout" ]]; then exit 1; fi
+      # - name: "[5] (token) Verify Outputs"
+      #   run: |
+      #     echo "Run Conclusion: ${{ steps.run-timeout-trigger-and-wait.outputs.run_conclusion }}"
+      #     if [[ "${{ steps.run-timeout-trigger-and-wait.outputs.run_conclusion }}" != "timeout" ]]; then exit 1; fi
 
-      - name: "[6] (github-app) Run Simple Trigger And Wait"
+      - name: '[6] (github-app) Run Simple Trigger And Wait'
         id: run-app-trigger-and-wait
         uses: dragoscops/workflow-trigger-wait@github_app_token
         with:
@@ -148,15 +148,15 @@ jobs:
               }
             }
           repo: ${{ github.repository }}
-          workflow_id: "test-workflow.yml"
-          ref: "main"
+          workflow_id: 'test-workflow.yml'
+          ref: 'main'
           inputs: '{"Timeout": "5"}'
-          wait_interval: "10000"
-          timeout: "60000"
-          action: "trigger-and-wait"
-          debug: "yes"
+          wait_interval: '10000'
+          timeout: '60000'
+          action: 'trigger-and-wait'
+          debug: 'yes'
 
-      - name: "[6] (github-app) Verify Outputs"
+      - name: '[6] (github-app) Verify Outputs'
         run: |
           echo "Run Conclusion: ${{ steps.run-app-trigger-and-wait.outputs.run_conclusion }}"
           if [[ "${{ steps.run-app-trigger-and-wait.outputs.run_conclusion }}" != "success" ]]; then exit 1; fi
